### ISSUE TITLE
Compile error for ESP32

### ISSUE THREAD

**Issue by linxcow** [ridencww/cww_MorseTx#2]
Trying to compile a little test on platformIO board ESP32  I get following errors:
I'm using v1.21 of the library
``
Dependency Graph
|-- CWW Morse Transmit @ 1.2.1
|-- WiFiClientSecure @ 2.0.0
|   |-- WiFi @ 2.0.0
Building in release mode
Compiling .pio/build/esp32dev/src/main.cpp.o
Compiling .pio/build/esp32dev/libc9e/CWW Morse Transmit/cww_MorseTx.cpp.o
.pio/libdeps/esp32dev/CWW Morse Transmit/cww_MorseTx.cpp: In member function 'void cww_MorseTx::dot()':
.pio/libdeps/esp32dev/CWW Morse Transmit/cww_MorseTx.cpp:103:24: error: call of overloaded 'tone(byte&, int&)' is ambiguous
     tone(_sndpin, _freq);
                        ^
In file included from .pio/libdeps/esp32dev/CWW Morse Transmit/cww_MorseTx.cpp:1:
/home/mint/.platformio/packages/framework-arduinoespressif32/cores/esp32/Arduino.h:206:6: note: candidate: 'void tone(uint8_t, unsigned int, long unsigned int)'
 void tone(uint8_t _pin, unsigned int frequency, unsigned long duration = 0);
      ^~~~
In file included from .pio/libdeps/esp32dev/CWW Morse Transmit/cww_MorseTx.cpp:3:
.pio/libdeps/esp32dev/CWW Morse Transmit/cww_MorseTx.h:10:6: note: candidate: 'void tone(uint8_t, unsigned int)'
 void tone(uint8_t pin, unsigned int frequency);
      ^~~~
.pio/libdeps/esp32dev/CWW Morse Transmit/cww_MorseTx.cpp: In member function 'void cww_MorseTx::dash()':
.pio/libdeps/esp32dev/CWW Morse Transmit/cww_MorseTx.cpp:119:24: error: call of overloaded 'tone(byte&, int&)' is ambiguous
     tone(_sndpin, _freq);
                        ^
In file included from .pio/libdeps/esp32dev/CWW Morse Transmit/cww_MorseTx.cpp:1:
/home/mint/.platformio/packages/framework-arduinoespressif32/cores/esp32/Arduino.h:206:6: note: candidate: 'void tone(uint8_t, unsigned int, long unsigned int)'
 void tone(uint8_t _pin, unsigned int frequency, unsigned long duration = 0);
      ^~~~
In file included from .pio/libdeps/esp32dev/CWW Morse Transmit/cww_MorseTx.cpp:3:
.pio/libdeps/esp32dev/CWW Morse Transmit/cww_MorseTx.h:10:6: note: candidate: 'void tone(uint8_t, unsigned int)'
 void tone(uint8_t pin, unsigned int frequency);
      ^~~~
*** [.pio/build/esp32dev/libc9e/CWW Morse Transmit/cww_MorseTx.cpp.o] Error 1
Compiling .pio/build/esp32dev/lib63f/WiFi/WiFiClient.cpp.o
============================================================================= [FAILED] Took 9.26 seconds =============================================================================>
``

**Comment by ridencww** [comment]
Library was originally written for Arduino and ESP8266. Had to add my own tone and noTone functions to support ESP32 (v1.x platform). Expressif has implemented tone and noTone in their 2.x platform, which caused the compile error. Modified code not to include my tone and noTone for ESP32 platforms greater than 2.x.

New v1.2.1 release created available for immediate download here and available in the Library Manager later today after the job runs to pick up the updated library.

**Comment by linxcow** [comment]
Thank you for looking into this , did you mean a new release 1.2.2 ? as i already have 1.2.1.

**Comment by ridencww** [comment]
I never created an actual Release for 1.2.1 a year ago. If I had done this properly, I would have created a Develop branch and then merged to Master and created a release, which I will do in the future.

Now that I have created an actual 1.2.1 Release, you can pull it down again from Github or wait for it to appear in the Arduino library manager. I tested the change with both 1.x and 2.x ESP32 platforms and everything works as expected now.

**Comment by linxcow** [comment]
Thank you for the update.
I'm using platformIO no update available at the moment for the library.
Does it take longer for the updates to be available in platformIO ?

**Comment by linxcow** [comment]
Update fixed for platformIO:

After adding following line to my plaftormio.ini config file , it updated the library and works great now.

    lib_deps = https://github.com/ridencww/cww_MorseTx.git # should also work to get the latest version.

**Comment by ridencww** [comment]
There is a job that runs hourly to scan for new or updated libraries. New versions are available to the Arduino IDE Library Manager about an hour after releasing, sometimes quicker.

Glad you got things working. Enjoy.
